### ISSUE TITLE
Bioc review

### ISSUE THREAD

**Issue by lgeistlinger** [waldronlab/CNVRanger#12]
Responsibilities as discussed:

*DESCRIPTION* (@lgeistlinger)

- [x] Minor: Consider using an Authors@R field instead of Author and Maintainer fields 
- [x] Add a BugReports field pointing to the GitHub issues page
- [x] BiocCheck will say to update your R dependency to 3.6.0

*NAMESPACE*

Looks good. You might want to rename importLRR_BAF to use 'camelCase' so
that it is consistent with other functions. (@viniciushdasilva rename to `importLrrBaf`)

*R/*

- [x] Consider providing support for MultiAssayExperiment inputs that contain
appropriate data for running cnvExprAssoc. @lgeistlinger 

- [x] .largest can be simplified to: @lgeistlinger 

```
.largest <- function(scores, ranges, qranges) {
    ind <- IRanges::which.max(GenomicRanges::width(ranges))
    vapply(seq_along(scores), function(i) scores[[i]][ind[i]], scores[[1]]) 
}
```

- Update the @param entry for all.paths @viniciushdasilva 
- Check inputs to avoid errors (plotManhattan) @viniciushdasilva 
- Consider using GRanges structures instead of data.frame in plotManhattan @viniciushdasilva 
- Avoid saving PDF files for the user by default, make the plot.pdf argument FALSE @viniciushdasilva 
- No need to use gc() explicitly @viniciushdasilva 
- Functions like setupCnvGWAS should make use of structures such as RaggedExperiment rather than a collection of files. @viniciushdasilva 
- Use names rather than integers to subset vectors and lists (ex. all.paths in prodGdsCnvLine:395) @viniciushdasilva 
- It is more efficient to make a call to rappdirs:::get_os() once than every time you need to check the OS, therefore, assign the result to an object and use the object for checking (prodGdsCnv). @viniciushdasilva 
- FWIW Perhaps GDSArray may help import GDS files (for importLRR_BAF)? @viniciushdasilva  
- [x] Vectorize where possible and use maps for matching and replacing (e.g., in replace gain / loss sections of .recodeCNVgenotype) @lgeistlinger 
- Try to avoid reading in the data from a file and accept the dataset as an argument so that users can read as they choose. @viniciushdasilva 
- Use TRUE and FALSE and not character versions of TRUE and FALSE @viniciushdasilva

**Comment by viniciushdasilva** [comment]
- [ ] Looks good. You might want to rename importLRR_BAF to use 'camelCase' so
that it is consistent with other functions. (@viniciushdasilva rename to `importLrrBaf`)

**Comment by lgeistlinger** [comment]
Everything addressed and resubmitted the revised version here:
https://github.com/Bioconductor/Contributions/issues/966#issuecomment-459987263
