### ISSUE TITLE
Questions - Input type

### ISSUE THREAD

**Issue by sagarutturkar** [waldronlab/CNVRanger#16]
Thank you for providing this tool and it seems very useful especially for it's ability to work with any diploid species as compared to GISTIC. I am working with CNVkit and have segmented CNV calls from multiple samples. Please see the snapshot below:

| Chromosome 	| start 	| end 	| sample 	| cn 	|
|------------	|------------	|-------------	|--------	|----	|
| chr1 	| 7,435 	| 1,129,028 	| T10 	| 2 	|
| chr1 	| 1,129,028 	| 122,678,785 	| T10 	| 2 	|
| chr2 	| 100 	| 4,368,377 	| T10 	| 2 	|
| chr2 	| 4,368,377 	| 4,440,739 	| T10 	| 2 	|
| chr2 	| 4,440,739 	| 4,469,134 	| T10 	| 2 	|
| chr2 	| 4,469,134 	| 4,657,825 	| T10 	| 2 	|
| chr1 	| 7,435 	| 122,678,785 	| T2 	| 2 	|
| chr2 	| 100 	| 14,439,486 	| T2 	| 1 	|
| chr2 	| 14,439,486 	| 14,449,562 	| T2 	| 2 	|
| chr2 	| 14,449,562 	| 21,877,348 	| T2 	| 1 	|
| chr2 	| 21,877,348 	| 21,881,012 	| T2 	| 2 	|
| chr2 	| 21,881,012 	| 23,457,436 	| T2 	| 1 	|
| chr2 	| 23,457,436 	| 23,464,764 	| T2 	| 2 	|
| chr2 	| 23,464,764 	| 26,984,008 	| T2 	| 1 	|
| chr2 	| 26,984,008 	| 26,990,420 	| T2 	| 3 	|
| chr1 	| 7,435 	| 122,678,785 	| T3 	| 2 	|
| chr2 	| 100 	| 2,517,195 	| T3 	| 2 	|
| chr2 	| 2,517,195 	| 4,747,590 	| T3 	| 2 	|
| chr2 	| 4,747,590 	| 4,808,045 	| T3 	| 2 	|
| chr2 	| 4,808,045 	| 5,288,931 	| T3 	| 3 	|
| chr2 	| 5,288,931 	| 5,322,822 	| T3 	| 2 	|
| chr2 	| 5,322,822 	| 5,533,496 	| T3 	| 3 	|
| chr2 	| 5,533,496 	| 5,841,062 	| T3 	| 1 	|
| chr2 	| 5,841,062 	| 5,924,417 	| T3 	| 2 	|
| chr2 	| 5,924,417 	| 6,366,842 	| T3 	| 2 	|
| chr2 	| 6,366,842 	| 18,423,139 	| T3 	| 2 	|
| chr2 	| 18,423,139 	| 18,980,063 	| T3 	| 2 	|
| chr2 	| 18,980,063 	| 20,078,338 	| T3 	| 2 	|
| chr2 	| 20,078,338 	| 21,716,133 	| T3 	| 2 	|
| chr2 	| 21,716,133 	| 23,024,171 	| T3 	| 2 	|
| chr1 	| 7,435 	| 122,678,785 	| T4 	| 2 	|
| chr2 	| 100 	| 2,426,513 	| T4 	| 2 	|
| chr2 	| 2,426,513 	| 3,714,372 	| T4 	| 2 	|
| chr2 	| 3,714,372 	| 4,259,376 	| T4 	| 2 	|
| chr2 	| 4,259,376 	| 4,308,839 	| T4 	| 2 	|
| chr2 	| 4,308,839 	| 4,348,226 	| T4 	| 2 	|
| chr2 	| 4,348,226 	| 4,447,151 	| T4 	| 2 	|
| chr2 	| 4,447,151 	| 4,560,732 	| T4 	| 2 	|
| chr2 	| 4,560,732 	| 4,621,186 	| T4 	| 2 	|
| chr2 	| 4,621,186 	| 5,070,013 	| T4 	| 2 	|
| chr2 	| 5,070,013 	| 5,088,332 	| T4 	| 2 	|
| chr2 	| 5,088,332 	| 5,272,443 	| T4 	| 2 	|
| chr2 	| 5,272,443 	| 5,668,855 	| T4 	| 2 	|
| chr2 	| 5,668,855 	| 5,682,595 	| T4 	| 3 	|
| chr2 	| 5,682,595 	| 5,777,858 	| T4 	| 2 	|
| chr2 	| 5,777,858 	| 5,896,937 	| T4 	| 2 	|

This is my first project with CNVkit and the segments I got seems to be very large while the example shown for the CNVRanger has very short intervals. 
1. What is the input type expected by CNVRanger (bin-level or segmented)? CNVkit has option to convert segmented calls to absolute integer copy numbers but not for the bin-level calls.
2. I am getting errors while running CNVRanger with above input file, Before I go into details, first I want to confirm my input is right.

**Comment by lgeistlinger** [comment]
Segmented copy number calls can be used as input (see also the [CNVRanger vignette, section 7.2](https://bioconductor.org/packages/devel/bioc/vignettes/CNVRanger/inst/doc/CNVRanger.html#application-to-tcga-data-stored-in-a-multiassayexperiment)).
However, your copy number calls seem to be indeed very large and come out as 2 (= diploid?), rather indicating that there is no copy number change in this region.
I recommend to try out a number of different callers (such as CNVnator and LUMPY) before proceeding to verify that these calls are correct.
