### ISSUE TITLE
Statistical test for Binary phenotype (A group- B group comparison)?

### ISSUE THREAD

**Issue by kysbbubbu** [waldronlab/CNVRanger#20]
Thank you for making nice tool.

Is there any way for statistical test for binary phenotype, not quantitative phenotype?
I want to compare CNV profiles between samples with phenotype A group and samples with phenotype B group.

**Comment by lgeistlinger** [comment]
@viniciushdasilva can you comment?

**Comment by viniciushdasilva** [comment]
The cnvGWAS() is currently based on PLINK as described in here: http://zzz.bwh.harvard.edu/plink/gvar.shtml

In your case you might be interested in the rare variants that are associated with group A, for example (http://zzz.bwh.harvard.edu/plink/cnv.shtml). However, this association of rare CNVs in a case/control design is not yet implemented in the cnvGWAS(). 

If you are not interested in rare CNVs, you can use cnvGWAS() just by tagging case as '0' and control as '1'. However, I would recommend that you try also other software that were specifically designed for case/control studies for comparison (e.g. CNVRuler).
