### ISSUE TITLE
Error while running cnvGWAS

### ISSUE THREAD

**Issue by eastreen** [waldronlab/CNVRanger#25]
I get this error when trying to run `cnvGWAS`:

```
> segs.pvalue.gr <- cnvGWAS(phen.info, chr.code.name=chr.code.name, method.m.test="none")
Error in stop_if_wrong_length("'seqnames'", ans_len) :
  'seqnames' must have the length of the object to construct (1) or length 1
```
I've been searching on the internet, if someone had encountered the same error, but haven't found anything :C

Here's the pipeline I've been running before this step:

```
cnv.calls <- read.csv("cnvs.for.CNVRanger.csv", as.is=TRUE, sep = "\t")

cnv.calls <- GenomicRanges::makeGRangesListFromDataFrame(cnv.calls, 
                                                         split.field="sample.id", keep.extra.columns=TRUE)
sort(cnv.calls)


phen.df <- read.csv("pheno.for.CNVRanger.csv", as.is=TRUE, sep = "\t")

re <- RaggedExperiment::RaggedExperiment(cnv.calls, colData=phen.df)

phen.info <- setupCnvGWAS("project1", phen.loc="pheno.for.CNVRanger.csv",
                          cnv.out.loc=re, map.loc = NULL)

chr.code.name <- data.frame(   
  V1 = c(23, 24), 
  V2 = c("X", "Y"))

segs.pvalue.gr <- cnvGWAS(phen.info, chr.code.name=chr.code.name, method.m.test="none")
```
Hope, you could help me out with this one :)

**Comment by lgeistlinger** [comment]
@viniciushdasilva can you take a look?

@eastreen: it will likely be helpful for @viniciushdasilva if you provide us with 

1. your `cnvs.for.CNVRanger.csv`
2. your `pheno.for.CNVRanger.csv`
3. the output of typing `sessionInfo()` in your R console after having carried out the above commands

in order for us to reproduce the issue.

Thanks!

**Comment by eastreen** [comment]
@viniciushdasilva would it be ok if I send you the files via email?

**Comment by viniciushdasilva** [comment]
@eastreen, yes you can send the files by email. Therefore, I will check on this issue and post any developments here.

**Comment by eastreen** [comment]
Could you provide me your email, please? Can't find it on your page

**Comment by lgeistlinger** [comment]
@eastreen you can find email adresses eg at the top of the [CNVRanger vignette](https://bioconductor.org/packages/release/bioc/vignettes/CNVRanger/inst/doc/CNVRanger.html).

**Comment by viniciushdasilva** [comment]
We have been planning a considerable upgrade in the `cnvGWAS()`. One of the main changes is going to be the replacement of linear regression in plink, which has been causing errors that are hard to solve, by the `lm()` internal R function. However, this is going to take some time to be pushed as a commit in the **main** `CNVRanger` branch. Thus, I would like to suggest an alternative solution using the **dev** branch.

The  **dev** branch is able to perform  `cnvGWAS()` with a linear mixed model with or without relationship matrices, but not a linear model like plink. However, the code below should retrieve a result pretty much similar to `lm()`. Nevertheless, I recommend this that you read more about the `lme4qtl` ([](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-018-2057-x)) works to might adapt your model to fit better with your data. 

```
data.folder <- "user/files"
pheno <- read.csv(file.path(data.folder,"pheno.for.CNVRanger.csv"), as.is=TRUE, sep = "\t")
ped <-pheno
ped$sire <- NA
ped$dam <- NA
ped$fam <- NA
ped <- subset(ped, select = c(sample.id, sire, dam, BT))

write.table(ped, file.path(data.folder,"ped.for.CNVRanger.csv"), sep="\t", col.names = TRUE, row.names = FALSE, quote=FALSE)

phen.info <- setupCnvGWAS("run", phen.loc=file.path(data.folder,"pheno.for.CNVRanger.csv"),
                          cnv.out.loc=file.path(data.folder, "cnvs.for.CNVRanger.csv"), 
                          pedigree.loc=file.path(data.folder,"ped.for.CNVRanger.csv"))

chr.code.name <- data.frame(   
  V1 = c(23, 24), 
  V2 = c("X", "Y"))

# I recommend 5% MAF due to your sample size - i.e. 68 
probes.cnv.gr <- prodGdsCnv(phen.info, chr.code.name=chr.code.name, freq.cn = 0.05)
probes.cnv.gr

model <- formula(BT ~ (1|sample.id))
segs.pvalue.gr <- cnvGWAS(phen.info, method.to.run="lmm", model = model, 
                          chr.code.name=chr.code.name, freq.cn = 0.05,
                          produce.gds = FALSE)
segs.pvalue.gr                          
```

**Comment by lgeistlinger** [comment]
Hi @viniciushdasilva I think it's best if you identify the differences in `cnvGWAS` in the `dev` branch and push the corresponding parts to the `master` branch. My concern with installation from the `dev` branch is that you indeed get latest functionality on `cnvGWAS` but will run into conflicts on all other parts of the package (which are outdated on the `dev` branch). So it sounds like the right time for me to get this migration going.

**Comment by viniciushdasilva** [comment]
Yes @lgeistlinger I agree that merging everything properly in the `master` branch is the best. It will be done accordingly, but as I said, it will take some time. I am presenting a solution in the `dev` as something temporary for users that cannot wait. Nevertheless, the `dev` branch should not present any conflicts as I frequently use it for my analyses smoothly. Moreover, I performed the `cnvGWAS`, from `dev` branch, with the files that @eastreen sent by email and it worked. Therefore, until I am able to properly merge `dev` and `master` branches, I recommend the `dev` branch for `cnvGWAS` with linear mixed models.

**Comment by viniciushdasilva** [comment]
`cnvGWAS` function in the `master` branch was updated and linear regression is now independent of PLINK. Thus, the error should be not present in CNVRanger 1.7.3.
