### ISSUE TITLE
LOH?

### ISSUE THREAD

**Issue by wangshun1121** [waldronlab/CNVRanger#32]
I wonder, how this package describe Loss of Heterogeneity(LOH) ?

**Comment by lgeistlinger** [comment]
I think you mean [loss of heterozygosity](https://en.wikipedia.org/wiki/Loss_of_heterozygosity). This is what we call a "heterozygous deletion" or "1-copy loss". See [Section 2](https://bioconductor.org/packages/release/bioc/vignettes/CNVRanger/inst/doc/CNVRanger.html#reading-and-accessing-cnv-data) of the CNVRanger vignette for how to encode such regions in the input format.

**Comment by wangshun1121** [comment]
I know what you mean: "1-copy loss", of course, since only 1 copy, there's nothing about heterozygosity. LOH, I want to say, of which the coverage is 2 not 1. When one copy of duel allele lost, the cell tried to repair the lost copy using another one, then such segments would become LOH, rather than "1-copy loss"

**Comment by lgeistlinger** [comment]
I think you are referring here to [copy-neutral LOH](https://en.wikipedia.org/wiki/Loss_of_heterozygosity#Copy-neutral_LOH). This is not modeled in the approaches implemented in CNVRanger, which work on changes in copy number only.
