### ISSUE TITLE
Is cnvEQTL function appropriated for transcript abundances from Salmon?

### ISSUE THREAD

**Issue by viniciushdasilva** [waldronlab/CNVRanger#33]
Hi @lgeistlinger,

In the help page of  `cnvEQTL` function it reads:

... it is typically recommended to exclude from the analysis (i) genes with fewer than r reads per million reads mapped ...
... Use the **min.cpm** and min.samples arguments, respectively....

I was not able to find the **min.cpm** argument. However, it seems that the number of genes in my output was drastically reduced in comparison with my input object (i.e. RangedSummarizedExperiment). Initially I had 23k but only 4k remained in the output. 

Could you check on that issue please? 

I have used Salmon quantification (https://combine-lab.github.io/salmon/) and not read counts per million. Should we think in a different filter parameter for Salmon quantification?

Best

**Comment by lgeistlinger** [comment]
Thanks for pointing that out. That is now the `filter.by.expr` argument. I need to adapt the documentation accordingly. You can set `filter.by.expr = FALSE` to not filter by expression but this will typically include a lot of noise, genes with too low of expression that it would make sense to test for differential expression. See `edgeR::filterByExpr` for details which is invoked under the hood when calling `cnvEQTL` with `filter.by.expr = TRUE`,

**Comment by lgeistlinger** [comment]
Also see the [tximport](https://bioconductor.org/packages/tximport) package for importing transcript abundances from salmon. I recommend using the `tximport` argument `countsFromAbundance="lengthScaledTPM"` or `"scaledTPM"`, and then to use the gene-level count matrix `txi$counts` directly as you would a regular count matrix as input for `cnvEQTL`.
