### ISSUE TITLE
Analysis of the results of CNV-GWAS

### ISSUE THREAD

**Issue by zonechen1994** [waldronlab/CNVRanger#36]
Hi! I have used CNVRanger to analysis my data with different phenotype. Now, i have a question about the results. After i run the following code : "segs.pvalue.gr <- cnvGWAS(phen.info, chr.code.name=chr.code.name, method.m.test="none")", I get a the segs.pvalue.gr. However, about the results, i have questions. What the meaning of "SegName", and what can I know the results of CNV is AMP of DEL for corresponding Phenotype? 

Thank you very much!

**Comment by viniciushdasilva** [comment]
Hi @zonechen1994, 

The segments are explained in the vignette but the concept is initially described in the paper 'Genome-Wide Detection of CNVs and Their Association with Meat Tenderness in Nelore Cattle'. 
(https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0157711)

Regarding your second question, the association is quantitative. So if a segment has loss and gains, the _p-value_ will reflect their joint effect on the phenotype. If you want to have separated p-values for loss and gains I recommend that you split your input beforehand and run two separated `cnvGWAS()` analysis. 

Sorry for missing your question!
