### ISSUE TITLE
QQ-plots using adjusted p-values

### ISSUE THREAD

**Issue by ddalfovo** [waldronlab/CNVRanger#40]
Hi!
I have obtained unexpected qqplots. Checking the code, I noticed that in the pheno_assoc.R file, at line 126, the qqplot are generated using the adjusted p-values.

`print(.qqunifPlot(segs.pvalue.gr$MinPvalueAdjusted, 
                        auto.key = list(corner = c(0.95, 0.05))))`
Here an example:
![image](https://github.com/waldronlab/CNVRanger/assets/28860508/6e803e31-4e4b-4672-ae3a-d3036b287029)

Shouldn't the QQ plot be generated using the unadjusted p-values instead of the adjusted p-values? In fact, if I try to manually plot the raw unadjusted pvalues, I obtain:
![image](https://github.com/waldronlab/CNVRanger/assets/28860508/0fa36646-79e7-477e-a06a-ccc9489fe227)

I might not have all the information, but based on my understanding, this plot appears to be accurate.

Thank you in advance,
Davide

**Comment by lgeistlinger** [comment]
Good catch @ddalfovo and thanks for reporting that. We've fixed that in CNVRanger 1.16.4 (Bioc release) and CNVRanger 1.17.4 (Bioc devel).
